### ISSUE TITLE
Wish the API was not so tightly woven to Streetview

### ISSUE THREAD

**Issue by devasur** [topheman/PanoramaSensorsViewer#2]
The best part of this API is its ability to compute right pitch and heading when initialized with a streetview.     Making those computed values available as a callback would have made this lib a great tool in many scenarios.  May be I could untangle it and refactor a bit.  Will be a lot faster if you had some time to consider a refactor.  Or is there something I am missing?

**Comment by topheman** [comment]
I think what you're talking about is already there :) . If you dive a little into the source code you'll see it's splitted in multiple modules : 

One of them is **deviceorientationHelper.js** - which can be used in standalone, with AMD (RequireJS) or CommonJS - on which **PanoramaSensorsViewers relies to manage deviceorientation listeneners AND have it uniform through all the platforms** (iPhone, Android, Chrome, Firefox, etc ...)

You'll find it here with other utilities I made that could also help you : https://github.com/topheman/PanoramaSensorsViewer/tree/master/src/js/topheman-panorama/utils

Note : As you'll see at the bottom of my [projects page](http://labs.topheman.com) I listed utilities I made along the time, I didn't put this one - don't remember why, maybe thought it was to tighten to PanoramaSensors - but I should add it to this list. Let me know if this helps you.

Tophe

**Comment by TimLewisMT** [comment]
Hi Boni, I always get your emails from WalkInto so I thought this discussion was on that.

I agree Topherman's api is very cool. I studied it before making this simple version of device orientation with street view here: https://github.com/TourSparkle/Map-Menu-Device-Orientation

**Comment by devasur** [comment]
@topheman Thank you.  After I left the note spent time reading your code and discovered deviceOrientationHelper.  In my context (I'm building the cardboard version of https://walkinto.in viewer)  require.js help was not 'required'  so was able to load it in easily and use with minor tweaks.  Thanks for your hard work.  I still have a few problems trying to iron out with sensitivity though.  But I am sure with some more time spent on it things should get better.  You could see a raw version of this work under development here

http://secure.walkinto.in/vr/e1HiXICitegJeri78RsKl

@timlewis500 my apologies in advance for spamming you.  Did not know about Toursparkle.  Very nice UI.  More power to you for making it open source.  Do you use WalkInto?  Are you a trusted photographer?

**Comment by TimLewisMT** [comment]
@devasur Hi, I started TourSparkle in 2013, meant to make it a customizable CMS for street view but never got to it. I am a trusted photographer. I don't use WalkInto, how goes it, lots of interest?

email me at: timlewis500@gmail.com

**Comment by topheman** [comment]
@devasur @timlewis500 I'm glad my project helped you (this is what Open Source Software means to me - helping each other and getting back to the community), thank you both for your feedbacks.

Tophe

**Comment by devasur** [comment]
@topheman +1
